// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKLlC7N_a5QToaWzdomjq7NiyqBNM6J8s',
    appId: '1:791439965118:web:77b3d8f8cfa861cb1657ef',
    messagingSenderId: '791439965118',
    projectId: 'location-share-app-12z',
    authDomain: 'location-share-app-12z.firebaseapp.com',
    storageBucket: 'location-share-app-12z.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-XNQDr6dxeANuybHvPr7EwFxLzPWRHkE',
    appId: '1:791439965118:android:d2774bce09a5a5b11657ef',
    messagingSenderId: '791439965118',
    projectId: 'location-share-app-12z',
    storageBucket: 'location-share-app-12z.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuZW4x01Of5ilL6t9xEHS0j5_9QR3ct58',
    appId: '1:791439965118:ios:6a64aed7a9f2f4c51657ef',
    messagingSenderId: '791439965118',
    projectId: 'location-share-app-12z',
    storageBucket: 'location-share-app-12z.firebasestorage.app',
    iosBundleId: 'com.example.locationShareApp',
  );

}